version: "3.1"

services:
  # photo-slide-front:
    # restart: always
    # build: ./front
    # ports:
      # - "3007:3000"
    # volumes:
      # - ./front:/usr/src
  
  photo-slide-database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: G4f2uj5674f6s6uip
      MYSQL_DATABASE: photo-slide
      MYSQL_USER: admin
      MYSQL_PASSWORD: f2uj56746
    container_name: photo-slide-database

  photo-slide-back:
    restart: always
    build: ./api
    command: "npm start"
    ports:
      - "8097:8097"
    volumes:
      - ./api:/user/app
    depends_on:
      - photo-slide-database


