version: "3.1"

services:

  photo-slide-database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: G4f2uj5674f6s6uip
      MYSQL_DATABASE: photo-slide
      MYSQL_USER: admin
      MYSQL_PASSWORD: f2uj56746
    container_name: photo-slide-database


